### ISSUE TITLE
Responsive sprites

### ISSUE THREAD

**Issue by pmaselkowski** [Maslosoft/Sprite#11]
Sprites could be created from larger icons - and scaled down for responsivity, ie:
Instead of:
```css
.icon-16-disk-black {
    background-position: -16px -112px;
}
```
Use percents:
```css
.icon-16-disk-black {
    background-position: 5.44% 47%;
}
```
