### ISSUE TITLE
Set vertical-align of icon class to baseline

### ISSUE THREAD

**Issue by pmaselkowski** [Maslosoft/Sprite#6]
CSS rule
```css
[class^="icon-16"]
```
Should have changed vertical align to baseline to fit better with larger fonts, ie:
```css
[class^="icon-16"], [class*=" icon-16"] {
    display: inline-block;
    overflow: hidden;
    vertical-align: baseline;
    line-height: 16px;
    width: 16px;
    height: 16px;
    background-repeat: no-repeat;
    background-image: url(sprite.png) !important;
}
```
